spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}

  app:
    frontend-url: ${FRONTEND_URL:https://edugen-app.vercel.app}
    api-url: ${API_URL:https://edugen.duckdns.org}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: ${MAIL_HOST:smtp.gmail.com}

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

storage:
  base-path: /app/pdfs

cors:
  allowed-origins:
    - ${CORS_ALLOWED_ORIGIN:https://edugen-app.vercel.app}

logging:
  level:
    dev.lucas.edugen: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

